version: '3'
services:
  app:
    build:
      context: ../../  # Verifique se o caminho está correto para a raiz do projeto
      dockerfile: docker/development/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Variáveis de ambiente que serão passadas para o container
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"  # Usar aspas duplas para garantir leitura correta
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
