spring.application.name=petdoc

# URL do banco de dados, usando a variável de ambiente para o nome do banco de dados
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}

# Usuário e senha do banco de dados definidos via variáveis de ambiente
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Configurações do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${SECRET_KEY}

# Configurações do Flyway para PostgreSQL
spring.flyway.enabled=true  # Ativa o Flyway
spring.flyway.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
spring.flyway.user=${POSTGRES_USER}  # Usuário do banco de dados, vindo das variáveis de ambiente
spring.flyway.password=${POSTGRES_PASSWORD}  # Senha do banco de dados

# Opcional: configurar o local dos scripts de migração, por padrão é classpath:db/migration. Ver 
# spring.flyway.locations=classpath:db/migration